import { generateReactHelpers } from "@uploadthing/react";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import type { OurFileRouter } from "~/server/uploadthing";

const { useUploadThing } = generateReactHelpers<OurFileRouter>();

const Home: NextPage = () => {
  const { getRootProps, getInputProps, isDragActive, files, startUpload } = useUploadThing('imageUploader');
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Upload
          </h1>
          <div {...getRootProps()} className="flex items-center flex-col gap-8 rounded bg-slate-600 p-8 text-white font-medium">
            <label className="bg-black px-12 py-4">
              <input {...getInputProps()} />
            </label>
            
            Drop files here!
            <div>
              {files.length > 0 && (
                <button className="rounded bg-blue-500 px-4 py-2" onClick={() => startUpload()}>
                  Upload {files.length} files
                </button>
              )}
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
